"""Independent settlement-label reconstruction (Phase 12C items 5 and 8).

    ŷ = UP   if P_end >= P_start
        DOWN if P_end <  P_start

...and compare it to Polymarket's actual resolved outcome.

A DISCREPANCY BETWEEN THE BRIEF AND THE LIVE MARKET RULES
---------------------------------------------------------
The brief states the current BTC five-minute rule as

    UP  <=>  ChainlinkBTC_end >= ChainlinkBTC_start

using the plain Chainlink reference price, and instructs that TWAP is a
predictive feature only - "Do not use Binance or TWAP as a substitute
settlement source."

The live market metadata on 2026-08-15 says something different. Every BTC
5-minute market fetched carried:

    "cryptoMarketConfigId": "btc-5m-twap-60",
    "cryptoMarketConfig": {"asset": "btc", "duration": "5m",
                           "twapEnabled": true, "twapLookbackSeconds": 60},
    "resolutionSource": "https://data.chain.link/streams/btc-usd-twap-60s-streams",
    "description": "This market will resolve to \\"Up\\" if the time-weighted
        average price (TWAP) of Bitcoin, generated by Chainlink, of the time
        range specified in the title is greater than or equal to the price at
        the beginning of that range..."

i.e. the settlement reference for these particular markets IS the Chainlink
BTC/USD 60-second TWAP stream, not the plain reference feed.

This module does not pick a side. It reconstructs the label under BOTH
bases for every round and reports both agreement rates:

  * `declared`  - the basis the market's own metadata declares
                  (`settlement_kind` / `twap_window_s` from discovery).
  * `reference` - the brief's plain-Chainlink-reference rule.

Whichever basis actually reproduces Polymarket's resolutions is then an
empirical result of the capture rather than an assumption baked into the
recorder, which is exactly what the Phase 12C approval gate needs to decide.
Binance is never used as a settlement basis under either reading - it is
recorded as a leading signal only.

Both readings agree on the comparison itself: `>=` resolves UP, so an
exactly-flat round is UP.
"""
from __future__ import annotations

from dataclasses import dataclass
from enum import Enum

from xamarinbot.realtime.rtds import (
    TOPIC_CHAINLINK,
    TOPIC_TWAP_30,
    TOPIC_TWAP_60,
    ReferenceObservation,
)


class Outcome(str, Enum):
    UP = "UP"
    DOWN = "DOWN"


class LabelStatus(str, Enum):
    """Whether a round's settlement label can be trusted for training.

    Phase 12C.1 item 15: if the metadata-declared rule, the resolution-source
    text, and the venue's resolved outcome disagree, the round is
    LABEL_AMBIGUOUS and must be excluded from training. A label nobody can
    reproduce is worse than no label, because it trains a model on noise
    while looking like signal.
    """

    CONFIRMED = "CONFIRMED"
    AMBIGUOUS = "LABEL_AMBIGUOUS"
    UNRESOLVED = "UNRESOLVED"

    @property
    def is_trainable(self) -> bool:
        return self is LabelStatus.CONFIRMED


#: Substrings that identify a settlement basis in a market's free-text
#: `resolutionSource` / rules description. Used only to CROSS-CHECK the
#: structured `cryptoMarketConfig`, never to override it.
_RULE_TEXT_MARKERS = {
    "chainlink_twap_60": ("twap-60s", "twap_60", "60s-streams", "60-second"),
    "chainlink_twap_30": ("twap-30s", "twap_30", "30s-streams", "30-second"),
}


def declared_basis_matches_rule_text(
    settlement_kind: str, twap_window_s: int | None, *texts: str | None
) -> bool | None:
    """Whether the market's free text agrees with its structured settlement
    configuration.

    Returns None when the text says nothing identifiable - "no evidence" is
    not "disagreement", and treating it as disagreement would mark every
    sparsely-described market ambiguous.
    """
    blob = " ".join(t.lower() for t in texts if t)
    if not blob:
        return None
    if settlement_kind != "chainlink_twap":
        # A plain-reference market should NOT be advertising a TWAP stream.
        mentions_twap = any(
            m in blob for markers in _RULE_TEXT_MARKERS.values() for m in markers
        )
        return not mentions_twap
    key = f"chainlink_twap_{twap_window_s}"
    markers = _RULE_TEXT_MARKERS.get(key)
    if markers is None:
        return None
    if any(m in blob for m in markers):
        return True
    # The text identifies SOME window, and it is not this one.
    other = any(
        m in blob for k, ms in _RULE_TEXT_MARKERS.items() if k != key for m in ms
    )
    return False if other else None


#: The only settlement rules this system can reconstruct. Gate A.0 item 8:
#: an unknown value must raise rather than silently becoming the plain
#: Chainlink reference.
SUPPORTED_SETTLEMENT_KINDS = frozenset({"chainlink_twap", "chainlink_reference"})


class UnsupportedSettlementKind(ValueError):
    """Raised for a settlement rule this system does not know how to
    reconstruct (Gate A.0 item 8)."""


def topic_for_basis(settlement_kind: str, twap_window_s: int | None) -> str:
    """The RTDS topic carrying the settlement reference series.

    `chainlink_twap` with window 60 -> `crypto_prices_twap_sixty`
    `chainlink_twap` with window 30 -> `crypto_prices_twap_thirty`
    `chainlink_reference`           -> `crypto_prices_chainlink`

    Anything else RAISES. The previous `return TOPIC_CHAINLINK` fall-through
    meant `"twap"`, `"foo"` or a malformed value silently selected the plain
    reference series as label truth - the same failure as guessing a missing
    rule, only quieter, because the round would still produce a confident
    label from the wrong price series.
    """
    if settlement_kind not in SUPPORTED_SETTLEMENT_KINDS:
        raise UnsupportedSettlementKind(
            f"unsupported settlement_kind {settlement_kind!r}; known values are "
            f"{sorted(SUPPORTED_SETTLEMENT_KINDS)}"
        )
    if settlement_kind == "chainlink_twap":
        if twap_window_s == 30:
            return TOPIC_TWAP_30
        if twap_window_s == 60:
            return TOPIC_TWAP_60
        raise UnsupportedSettlementKind(
            f"chainlink_twap declares window {twap_window_s}s; RTDS publishes only 30 and 60"
        )
    return TOPIC_CHAINLINK


@dataclass(frozen=True)
class BasisReconstruction:
    """One basis's attempt at reconstructing the round's label."""

    basis: str  # "declared" | "reference"
    topic: str
    start_value: float | None
    end_value: float | None
    start_obs_ts_ns: int | None
    end_obs_ts_ns: int | None
    #: How far the observation actually used sits from the exact round
    #: boundary, in seconds. A large value means the reconstruction rests on
    #: a poor proxy for the boundary and should not be trusted.
    start_offset_s: float | None
    end_offset_s: float | None
    outcome: Outcome | None
    reason: str

    @property
    def is_reconstructed(self) -> bool:
        return self.outcome is not None


@dataclass(frozen=True)
class LabelReconstruction:
    round_id: str
    declared: BasisReconstruction
    reference: BasisReconstruction
    reported_outcome: Outcome | None
    reported_source: str | None
    #: Phase 12C.1 item 15: does the market's free-text rule agree with its
    #: structured settlement configuration? None = the text said nothing
    #: identifiable, which is not disagreement.
    rule_text_agrees: bool | None = None

    @property
    def status(self) -> "LabelStatus":
        """CONFIRMED only when everything that can be checked agrees.

        AMBIGUOUS when the declared basis reproduces a DIFFERENT outcome from
        the one the venue published, or when the market's own rule text
        contradicts its structured configuration. Such a round is excluded
        from training rather than being labelled by majority vote.
        """
        if self.reported_outcome is None or self.declared.outcome is None:
            return LabelStatus.UNRESOLVED
        if self.declared.outcome is not self.reported_outcome:
            return LabelStatus.AMBIGUOUS
        if self.rule_text_agrees is False:
            return LabelStatus.AMBIGUOUS
        return LabelStatus.CONFIRMED

    @property
    def is_trainable(self) -> bool:
        return self.status.is_trainable

    @property
    def declared_agrees(self) -> bool | None:
        if self.reported_outcome is None or self.declared.outcome is None:
            return None
        return self.declared.outcome is self.reported_outcome

    @property
    def reference_agrees(self) -> bool | None:
        if self.reported_outcome is None or self.reference.outcome is None:
            return None
        return self.reference.outcome is self.reported_outcome

    @property
    def bases_agree(self) -> bool | None:
        """Whether the two readings even produce the same label. When they
        do, the discrepancy above is moot for that round; when they don't,
        the round is a discriminating observation."""
        if self.declared.outcome is None or self.reference.outcome is None:
            return None
        return self.declared.outcome is self.reference.outcome


def _pick(
    observations: list[ReferenceObservation],
    boundary_ns: int,
    *,
    at_or_before: bool,
    tolerance_s: float,
) -> tuple[ReferenceObservation | None, float | None]:
    """The observation closest to `boundary_ns` on the required side.

    The start reference must be the last observation at or BEFORE the round
    opens, and the end reference the first at or AFTER it closes - matching
    how a settlement oracle reads a window boundary. Selection is by SOURCE
    timestamp, never receive time (item 4).
    """
    best: ReferenceObservation | None = None
    for obs in observations:
        if at_or_before:
            if obs.source_ts_ns <= boundary_ns and (best is None or obs.source_ts_ns > best.source_ts_ns):
                best = obs
        else:
            if obs.source_ts_ns >= boundary_ns and (best is None or obs.source_ts_ns < best.source_ts_ns):
                best = obs
    if best is None:
        return None, None
    offset_s = abs(best.source_ts_ns - boundary_ns) / 1e9
    if offset_s > tolerance_s:
        return None, offset_s
    return best, offset_s


def reconstruct_basis(
    basis: str,
    topic: str,
    observations: list[ReferenceObservation],
    start_ts: float,
    end_ts: float,
    tolerance_s: float = 5.0,
) -> BasisReconstruction:
    """Reconstruct one basis's label from that basis's observation series."""
    if not observations:
        return BasisReconstruction(
            basis, topic, None, None, None, None, None, None, None,
            f"no {topic} observations captured for this round",
        )
    start_ns = int(start_ts * 1e9)
    end_ns = int(end_ts * 1e9)
    start_obs, start_off = _pick(observations, start_ns, at_or_before=True, tolerance_s=tolerance_s)
    end_obs, end_off = _pick(observations, end_ns, at_or_before=False, tolerance_s=tolerance_s)

    if start_obs is None or end_obs is None:
        missing = []
        if start_obs is None:
            missing.append(f"start (nearest offset {start_off}s)" if start_off is not None else "start (none at or before)")
        if end_obs is None:
            missing.append(f"end (nearest offset {end_off}s)" if end_off is not None else "end (none at or after)")
        return BasisReconstruction(
            basis, topic,
            start_obs.value if start_obs else None,
            end_obs.value if end_obs else None,
            start_obs.source_ts_ns if start_obs else None,
            end_obs.source_ts_ns if end_obs else None,
            start_off, end_off, None,
            "cannot reconstruct: missing boundary observation for " + ", ".join(missing),
        )

    # Prefer the venue's own full-accuracy value where available: the
    # rounded `value` float can straddle a tie that the E18 value resolves
    # cleanly, and a 5-minute BTC round can genuinely be flat to several
    # decimal places.
    start_v = start_obs.full_accuracy_value if start_obs.full_accuracy_value is not None else start_obs.value
    end_v = end_obs.full_accuracy_value if end_obs.full_accuracy_value is not None else end_obs.value
    outcome = Outcome.UP if end_v >= start_v else Outcome.DOWN
    return BasisReconstruction(
        basis, topic, start_v, end_v,
        start_obs.source_ts_ns, end_obs.source_ts_ns,
        start_off, end_off, outcome,
        f"P_end={end_v!r} {'>=' if outcome is Outcome.UP else '<'} P_start={start_v!r}",
    )


def reconstruct_label(
    round_id: str,
    settlement_kind: str,
    twap_window_s: int | None,
    observations_by_topic: dict[str, list[ReferenceObservation]],
    start_ts: float,
    end_ts: float,
    reported_outcome: Outcome | None = None,
    reported_source: str | None = None,
    tolerance_s: float = 5.0,
    resolution_source: str | None = None,
    description: str | None = None,
) -> LabelReconstruction:
    """Reconstruct under BOTH bases and compare each to the venue's result.

    `resolution_source`/`description` are the market's own free text; when
    supplied they are cross-checked against its structured settlement
    configuration, and a contradiction marks the round LABEL_AMBIGUOUS
    (item 15).
    """
    declared_topic = topic_for_basis(settlement_kind, twap_window_s)
    declared = reconstruct_basis(
        "declared", declared_topic, observations_by_topic.get(declared_topic, []),
        start_ts, end_ts, tolerance_s,
    )
    reference = reconstruct_basis(
        "reference", TOPIC_CHAINLINK, observations_by_topic.get(TOPIC_CHAINLINK, []),
        start_ts, end_ts, tolerance_s,
    )
    return LabelReconstruction(
        round_id=round_id,
        declared=declared,
        reference=reference,
        reported_outcome=reported_outcome,
        reported_source=reported_source,
        rule_text_agrees=declared_basis_matches_rule_text(
            settlement_kind, twap_window_s, resolution_source, description
        ),
    )


def reported_outcome_from_gamma(gamma: dict) -> tuple[Outcome | None, str | None]:
    """Polymarket's own resolved outcome, read from a settled Gamma payload.

    Uses `umaResolutionStatuses`/`outcomePrices` only once the market is
    actually closed: an open market's `outcomePrices` is the live mid, not a
    resolution, and treating it as one would fabricate labels for every
    round. Returns (None, reason) when the market has not settled.
    """
    import json as _json

    if not gamma.get("closed"):
        return None, "market not closed"
    prices = gamma.get("outcomePrices")
    outcomes = gamma.get("outcomes")
    if isinstance(prices, str):
        try:
            prices = _json.loads(prices)
        except _json.JSONDecodeError:
            prices = None
    if isinstance(outcomes, str):
        try:
            outcomes = _json.loads(outcomes)
        except _json.JSONDecodeError:
            outcomes = None
    if not prices or not outcomes or len(prices) != len(outcomes):
        return None, "closed market carried no usable outcomePrices/outcomes"

    winners = [
        (str(label), float(p))
        for label, p in zip(outcomes, prices)
        if float(p) >= 0.99
    ]
    if len(winners) != 1:
        return None, f"no unambiguous winning outcome in {list(zip(outcomes, prices))}"
    label = winners[0][0].strip().lower()
    if label in ("up", "yes"):
        return Outcome.UP, "gamma_outcome_prices"
    if label in ("down", "no"):
        return Outcome.DOWN, "gamma_outcome_prices"
    return None, f"winning outcome label {winners[0][0]!r} is not up/down"


def reported_outcome_from_clob(clob: dict) -> tuple[Outcome | None, str | None]:
    """Polymarket's resolution as exposed by CLOB market-info's
    `tokens[].winner` flag.

    LIVE FINDING (2026-08-15): this flag LAGS Gamma's `outcomePrices`. For a
    round that ended 459s earlier, Gamma already reported `closed: true` with
    prices `["1", "0"]` while every CLOB token still had `winner: false`; by
    759s both agreed. So this is a useful independent cross-check but a poor
    primary source, and it is consulted after Gamma rather than before.
    """
    if not clob.get("closed"):
        return None, "CLOB market-info does not report the market closed"
    winners = [t for t in (clob.get("tokens") or []) if t.get("winner")]
    if len(winners) != 1:
        return None, f"CLOB market-info has {len(winners)} winning tokens; expected exactly 1"
    label = str(winners[0].get("outcome", "")).strip().lower()
    if label in ("up", "yes"):
        return Outcome.UP, "clob_token_winner"
    if label in ("down", "no"):
        return Outcome.DOWN, "clob_token_winner"
    return None, f"winning CLOB outcome label {winners[0].get('outcome')!r} is not up/down"


def reported_outcome_from_market_resolved(payload: dict) -> tuple[Outcome | None, str | None]:
    """Polymarket's resolution as announced on the CLOB market channel's
    `market_resolved` event, when one was captured."""
    for key in ("winning_outcome", "outcome", "winner"):
        val = payload.get(key)
        if isinstance(val, str):
            t = val.strip().lower()
            if t in ("up", "yes"):
                return Outcome.UP, "market_resolved_event"
            if t in ("down", "no"):
                return Outcome.DOWN, "market_resolved_event"
    return None, "market_resolved event carried no recognizable winning outcome"


def summarize_agreement(reconstructions: list[LabelReconstruction]) -> dict:
    """Capture-level label-agreement summary for the item 15 report."""
    def rate(flags: list[bool | None]) -> tuple[int, int, float | None]:
        decided = [f for f in flags if f is not None]
        agreed = sum(1 for f in decided if f)
        return agreed, len(decided), (agreed / len(decided) if decided else None)

    d_ok, d_n, d_rate = rate([r.declared_agrees for r in reconstructions])
    r_ok, r_n, r_rate = rate([r.reference_agrees for r in reconstructions])
    b_ok, b_n, b_rate = rate([r.bases_agree for r in reconstructions])
    return {
        "rounds": len(reconstructions),
        "declared_basis_agreed": d_ok,
        "declared_basis_comparable": d_n,
        "declared_basis_agreement_rate": d_rate,
        "reference_basis_agreed": r_ok,
        "reference_basis_comparable": r_n,
        "reference_basis_agreement_rate": r_rate,
        "bases_agreed_with_each_other": b_ok,
        "bases_comparable": b_n,
        "bases_agreement_rate": b_rate,
        # The gate the brief cares about: can we reproduce Polymarket's
        # labels at all? If neither basis reaches 100% on a clean capture,
        # the q model must not be trained (item 8).
        "labels_reproducible": (d_rate == 1.0 if d_rate is not None else False)
        or (r_rate == 1.0 if r_rate is not None else False),
        # Phase 12C.1 item 15: rounds excluded from training because their
        # declared rule, rule text and venue outcome do not all agree.
        "confirmed": sum(1 for r in reconstructions if r.status is LabelStatus.CONFIRMED),
        "label_ambiguous": sum(1 for r in reconstructions if r.status is LabelStatus.AMBIGUOUS),
        "unresolved": sum(1 for r in reconstructions if r.status is LabelStatus.UNRESOLVED),
        "trainable_round_ids": [r.round_id for r in reconstructions if r.is_trainable],
    }
